<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once __DIR__ . '/../config/email_config.php';

// Ensure Composer autoload is available
$autoload = dirname(__DIR__) . '/vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
}

/**
 * Send a simple HTML email via PHPMailer based on SMTP settings from config/email_config.php
 * This is best-effort: returns true on success, false on failure.
 */
function sendEmail(string $toEmail, string $subject, string $htmlBody, string $toName = ''): bool {
    if (empty($toEmail)) {
        return false;
    }
    try {
        $mail = new PHPMailer(true);
        $mail->isSMTP();
        $mail->Host = SMTP_HOST;
        $mail->SMTPAuth = true;
        $mail->Username = SMTP_USERNAME;
        $mail->Password = SMTP_PASSWORD;
        $mail->Port = SMTP_PORT;
        $secure = strtolower((string) SMTP_SECURE);
        if ($secure === 'ssl' || $secure === 'tls') {
            $mail->SMTPSecure = $secure;
        }
        $mail->CharSet = 'UTF-8';

        $mail->setFrom(SMTP_FROM_EMAIL, SMTP_FROM_NAME);
        $mail->addAddress($toEmail, $toName);

        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body = $htmlBody;

        $mail->AltBody = strip_tags(str_replace(['<br>', '<br/>', '<br />'], "\n", $htmlBody));

        $mail->send();
        return true;
    } catch (\Throwable $e) {
        // Optionally log: error suppressed to avoid blocking workflows
        return false;
    }
}

/**
 * Helper to render a simple attendance email body
 */
function renderAttendanceEmailBody(array $data): string {
    // expected keys: student_name, action, status, schedule_label, timestamp
    $student = htmlspecialchars($data['student_name'] ?? 'Student');
    $action = strtoupper(htmlspecialchars($data['action'] ?? ''));
    $status = htmlspecialchars($data['status'] ?? '');
    $schedule = htmlspecialchars($data['schedule_label'] ?? '');
    $ts = htmlspecialchars($data['timestamp'] ?? '');

    return "<div style=\"font-family:Arial,sans-serif;line-height:1.5\">" .
           "<h3 style=\"margin:0 0 10px\">Attendance $action recorded</h3>" .
           "<p style=\"margin:0 0 6px\"><strong>Student:</strong> $student</p>" .
           "<p style=\"margin:0 0 6px\"><strong>Status:</strong> $status</p>" .
           ($schedule !== '' ? "<p style=\"margin:0 0 6px\"><strong>Class:</strong> $schedule</p>" : '') .
           ($ts !== '' ? "<p style=\"margin:0 0 6px\"><strong>Time:</strong> $ts</p>" : '') .
           "<p style=\"margin-top:12px;color:#555\">This message was generated by Attendance System Pro.</p>" .
           "</div>";
}
